### ISSUE TITLE
Melhorar performance no reconhecimento de imagem

### ISSUE THREAD

**Issue by mario0vasconcelos** [Nunoc99/SAVI-TP1#4]
O reconhecimento das caras está a ser feito apenas por 1 core do CPU (verificado pelo System Monitor).
Está na documentação da biblioteca face_recognition_models um tópico a explicar como solucionar o problema e implementa-lo se possível.

https://github.com/ageitgey/face_recognition_models

**Comment by JoseSilva23** [comment]
Os múltiplos cores de CPU só se aplicam à procura das imagens nas pastas e não no processamento do código.

**Comment by mario0vasconcelos** [comment]
Ok
